language: dart

dart: [stable, dev]

env:
  global:
    - LIBS="lib test"
  jobs:
    - TASK="dartanalyzer --fatal-warnings $LIBS analysis_options.yaml"
    - TASK="pub run test"
    - TASK="tool/builder_test.sh"
    - TASK="dartfmt --set-exit-if-changed -n $LIBS"

dart_task: []

jobs:
  exclude:
    - dart: dev
      env:  TASK="dartfmt --set-exit-if-changed -n $LIBS"

script: [pub get, $TASK]

cache:
  directories:
    - $HOME/.pub-cache

# Only run Travis jobs for named branches (to avoid double builds for each PR)
branches:
  only: [master, /^\d(\.x|-dev)$/, /travis-build/]
