builders:
  code_excerpter:
    import: 'package:code_excerpter/builder.dart'
    builder_factories: [builder]
    build_extensions: {'': [.excerpt.yaml]}
    defaults:
      generate_for:
#        include:
#          - lib/**
#          - web/**
#          - test/**
#          - example/**
#          - examples/**
        exclude:
          - '**/.*/**'
          - '**/.DS_Store'
          - '**/build/**'
          - '**/node_modules/**'
          - '**/*.bmp'
          - '**/*.jpg'
          - '**/*.jpeg'
          - '**/*.png'
          - '**/*.tiff'
