name: code_excerpter
version: 0.4.1
description: A line-based utility for extracting code regions.

author: Patrice Chalin <pchalin@gmail.com>
homepage: https://github.com/chalin/code_excerpt_updater

environment:
  sdk: '>=2.0.0-dev.67.0 <2.0.0'

dependencies:
  build: ^0.12.0
  logging: ^0.11.3+1
  path: ^1.6.0
  yaml: ^2.1.0

dev_dependencies:
  build_runner: ^0.9.0
  test: ^1.0.0
