name: code_excerpter
version: 0.3.1+2
description: A line-based utility for extracting code regions.

author: Patrice Chalin <pchalin@gmail.com>
homepage: https://github.com/chalin/code_excerpt_updater

environment:
  sdk: '>=2.0.0-dev.61.0 <2.0.0'

dependencies:
  build: ^0.12.0
  logging: ^0.11.3+1
  path: ^1.6.0
  yaml: ^2.1.0

dev_dependencies:
  build_runner: ^0.8.9
  test: ^0.12.40
